# Generated by Django 2.2.4 on 2023-01-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reads_App', '0002_auto_20221231_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.FloatField(),
        ),
    ]
